#!/usr/bin/env python3
"""Generate src/hpgl_font.cpp from the stick-font table.

The HP-GL LB (label) command draws text with the plotter's built-in single-
stroke "stick" font, which is fixed-width: every character is designed to fill
the same box, and the pen advances one character cell regardless of the glyph.

Usage:
    tools/gen_hpgl_font.py [path/to/stick_font.json] > src/hpgl_font.cpp

The font defaults to the copy vendored next to this script, so regenerating
needs nothing installed beyond Python.

Input format: {"<character>": [[[x, y], ...], ...]} — one polyline list per
glyph, in design units where x runs 0..4 across the character and y runs 0..8
from the baseline to the cap height (descenders and accents fall outside).

Keys are single characters, indexed here by their code point: HPGL is a byte
stream, so a glyph is addressed by the byte that selects it and the range above
126 follows HP's Roman-8 encoding rather than Latin-1.  Characters that no
single byte can address (code point > 255) therefore cannot be used.
"""

import json
import os
import sys

DEFAULT_FONT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "stick_font.json")

FIRST, LAST = 32, 255


def fmt(v):
    s = "%g" % v
    return s + ("f" if "." in s else ".f")


def label(code):
    if code == 32:
        return "space"
    if 33 <= code <= 126:
        return chr(code)
    return "0x%02x" % code


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_FONT
    with open(path, encoding="utf-8") as f:
        table = json.load(f)

    unaddressable = [k for k in table if len(k) != 1 or ord(k) > LAST]
    if unaddressable:
        sys.exit("glyph keys no byte can address: %r" % unaddressable)
    glyphs = {ord(k): v for k, v in table.items()}

    missing = [c for c in range(FIRST, 127) if c not in glyphs]
    if missing:
        sys.exit("missing ASCII glyphs: %r" % [chr(c) for c in missing])

    xy, strokes, rows = [], [], []
    for code in range(FIRST, LAST + 1):
        polylines = [p for p in glyphs.get(code, []) if len(p) >= 2]
        first = len(strokes)
        for pts in polylines:
            strokes.append((len(xy) // 2, len(pts)))
            for x, y in pts:
                xy += [x, y]
        rows.append((code, first, len(polylines)))

    out = sys.stdout.write
    out("// Generated by tools/gen_hpgl_font.py — do not edit by hand.\n")
    out("//\n")
    out("// Fixed-width single-stroke plotter font, from tools/stick_font.json.\n")
    out("// Hershey-derived, by Alex Forencich with additions by Marcel Schwittlick.\n")
    out("// Acknowledgements required by the Hershey Fonts licence:\n")
    out("//   - The Hershey Fonts were originally created by Dr. A. V. Hershey\n")
    out("//     while working at the U. S. National Bureau of Standards.\n")
    out("//   - The format of the Font data in this distribution was originally\n")
    out("//     created by James Hurt, Cognition, Inc., 900 Technology Park Drive,\n")
    out("//     Billerica, MA 01821 (mit-eddie!ci-dandelion!hurt)\n")
    out("\n#include \"hpgl_font.h\"\n\nnamespace hpgl_font {\nnamespace {\n\n")

    out("// Flat x,y coordinate pool in font design units.\n")
    out("const float kXY[] = {\n")
    for i in range(0, len(xy), 12):
        out("    " + " ".join(fmt(v) + "," for v in xy[i:i + 12]) + "\n")
    out("};\n\n")

    out("const FontStroke kStrokes[] = {\n")
    for i in range(0, len(strokes), 6):
        chunk = strokes[i:i + 6]
        out("    " + " ".join("{kXY + %d, %d}," % (o * 2, n) for o, n in chunk) + "\n")
    out("};\n\n")

    out("// One entry per byte value %d..%d.  Codes with no glyph are blank.\n"
        % (FIRST, LAST))
    out("const FontGlyph kGlyphs[] = {\n")
    for code, first, count in rows:
        entry = "    {kStrokes + %d, %d}," % (first, count)
        out("%-30s// '%s'\n" % (entry, label(code)))
    out("};\n\n} // namespace\n\n")

    out("""const FontGlyph &glyph(unsigned char c) {
  if (c < %d)
    return kGlyphs[0]; // control character → blank, like space
  return kGlyphs[c - %d];
}

} // namespace hpgl_font
""" % (FIRST, FIRST))


if __name__ == "__main__":
    main()
