#!/usr/bin/env python3
"""Generate src/hpgl_font.cpp from an SVG stroke font.

The HP-GL LB (label) command draws text with the plotter's built-in single-
stroke "stick" font.  We approximate it with the Hershey Sans 1-stroke font,
the public-domain vector font plotters have historically been paired with.

Usage:
    tools/gen_hpgl_font.py [path/to/font.svg] > src/hpgl_font.cpp

The font defaults to the copy vendored next to this script, so regenerating
needs nothing installed beyond Python.  Only ASCII 32..126 is emitted; those
glyphs are pure polylines (the accented glyphs, which use Bezier curves, are
skipped).
"""

import html
import os
import re
import sys

DEFAULT_SVG = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "HersheySans1.svg")

FIRST, LAST = 32, 126


def parse_glyphs(svg):
    """Return {codepoint: (advance, [polyline, ...])} for the ASCII range."""
    glyphs = {}
    for tag in re.findall(r"<glyph ([^>]*?)/>", svg, re.S):
        attrs = dict(re.findall(r'([a-z-]+)="(.*?)"', tag, re.S))
        uni = html.unescape(attrs.get("unicode", ""))
        if len(uni) != 1 or not FIRST <= ord(uni) <= LAST:
            continue
        polylines = []
        for sub in attrs.get("d", "").split("M"):
            nums = [float(n) for n in sub.replace("L", " ").split()]
            if len(nums) >= 4:
                polylines.append(list(zip(nums[0::2], nums[1::2])))
        glyphs[ord(uni)] = (float(attrs["horiz-adv-x"]), polylines)
    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        sys.exit("missing glyphs: %r" % [chr(c) for c in missing])
    return glyphs


def fmt(v):
    s = "%g" % v
    return s + ("f" if "." in s else ".f")


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SVG
    with open(path, encoding="utf-8") as f:
        glyphs = parse_glyphs(f.read())

    uppercase = [glyphs[c][0] for c in range(ord("A"), ord("Z") + 1)]
    cell_width = sum(uppercase) / len(uppercase)

    xy, strokes, rows = [], [], []
    for code in range(FIRST, LAST + 1):
        advance, polylines = glyphs[code]
        first = len(strokes)
        for pts in polylines:
            strokes.append((len(xy) // 2, len(pts)))
            for x, y in pts:
                xy += [x, y]
        rows.append((code, advance, first, len(polylines)))

    out = sys.stdout.write
    out("// Generated by tools/gen_hpgl_font.py — do not edit by hand.\n")
    out("//\n")
    out("// Hershey Sans 1-stroke, from tools/HersheySans1.svg.\n")
    out("// Acknowledgements required by the Hershey Fonts licence:\n")
    out("//   - The Hershey Fonts were originally created by Dr. A. V. Hershey\n")
    out("//     while working at the U. S. National Bureau of Standards.\n")
    out("//   - The format of the Font data in this distribution was originally\n")
    out("//     created by James Hurt, Cognition, Inc., 900 Technology Park Drive,\n")
    out("//     Billerica, MA 01821 (mit-eddie!ci-dandelion!hurt)\n")
    out("\n#include \"hpgl_font.h\"\n\nnamespace hpgl_font {\nnamespace {\n\n")

    out("// Flat x,y coordinate pool in font design units.\n")
    out("const float kXY[] = {\n")
    for i in range(0, len(xy), 12):
        out("    " + " ".join(fmt(v) + "," for v in xy[i:i + 12]) + "\n")
    out("};\n\n")

    out("const FontStroke kStrokes[] = {\n")
    for i in range(0, len(strokes), 6):
        chunk = strokes[i:i + 6]
        out("    " + " ".join("{kXY + %d, %d}," % (o * 2, n) for o, n in chunk) + "\n")
    out("};\n\n")

    out("// One entry per ASCII code %d..%d.\n" % (FIRST, LAST))
    out("const FontGlyph kGlyphs[] = {\n")
    for code, advance, first, count in rows:
        label = "space" if code == 32 else chr(code)
        entry = "    {%s, kStrokes + %d, %d}," % (fmt(advance), first, count)
        out("%-38s// '%s'\n" % (entry, label))
    out("};\n\n} // namespace\n\n")

    out("const float kCellWidth = %s; // mean A-Z advance\n" % fmt(cell_width))
    out("""
const FontGlyph &glyph(unsigned char c) {
  if (c < %d || c > %d)
    return kGlyphs[0]; // unprintable → blank, same metrics as space
  return kGlyphs[c - %d];
}

} // namespace hpgl_font
""" % (FIRST, LAST, FIRST))


if __name__ == "__main__":
    main()
